spring.application.name=product-service
server.port=8081
#spring.mongodb.uri=mongodb://root:password@mongodb:27017/product_service?authSource=admin
spring.mongodb.uri=mongodb+srv://mongo:mongo@product-service.xpjlro2.mongodb.net/product-service
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs


management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=product-service
management.tracing.sampling.probability=1.0

# Loki URL
