spring.application.name=order-service
#spring.datasource.url=jdbc:mysql:///order-service?cloudSqlInstance=springboot4-microservices:us-central1:mysql-prod&socketFactory=com.google.cloud.sql.mysql.SocketFactory
spring.cloud.gcp.sql.instance-connection-name=springboot4-microservices:us-central1:mysql-prod
spring.cloud.gcp.sql.database-name=order-service
#spring.datasource.username=root
#spring.datasource.password=Mysql123!
spring.jpa.hibernate.ddl-auto=none
server.port=8082
inventory.service.url=http://localhost:8083
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

#Kafka Properties
#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=order-placed
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=http://localhost:8085

spring.cloud.gcp.project-id=springboot4-microservices
spring.cloud.pubsub.emulator-enabled= false
spring.cloud.gcp.sql.enabled=true