spring.application.name=notification-service

server.port=${PORT:8080}
server.address=0.0.0.0

# Mail (OK for Cloud Run)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=70db54c078d8c8
spring.mail.password=b0e4b1432fae4e
spring.mail.protocol=smtp

# GCP Pub/Sub (keep only this, NOT Kafka)
spring.cloud.gcp.project-id=springboot4-microservices
spring.cloud.pubsub.emulator-enabled=false

