name: ci-cd-pipeline

on:
  push:
    branches: ["main", "eks"]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  ECR_REGISTRY: 741458575095.dkr.ecr.us-west-2.amazonaws.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # CHECKOUT
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # IMAGE TAG
      # -------------------------
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # -------------------------
      # JAVA SETUP
      # -------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # -------------------------
      # AWS AUTH
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------------------------
      # EKS KUBECONFIG
      # -------------------------
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name springboot-microservices \
            --region $AWS_REGION

      # -------------------------
      # ECR LOGIN
      # -------------------------
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -------------------------
      # BUILD & PUSH IMAGES
      # -------------------------
      - name: Build & Push Images
        run: |
          SERVICES="order-service product-service inventory-service notification-service api-gateway"

          for svc in $SERVICES
          do
            docker build -t $ECR_REGISTRY/$svc:$IMAGE_TAG ./services/$svc
            docker push $ECR_REGISTRY/$svc:$IMAGE_TAG
          done

      # -------------------------
      # INSTALL HELM + HELMFILE
      # -------------------------
      - name: Setup Helmfile
        uses: mamezou-tech/setup-helmfile@v2.0.0
        with:
         helmfile-version: "v0.169.1" # Optional: specify version
         install-helm: yes


          

      # -------------------------
      # DEPLOY
      # -------------------------
      - name: Run Helmfile Apply
        uses: helmfile/helmfile-action@v1.9.1
        with:
          helmfile-args: apply


      # -------------------------
      # VERIFY DEPLOYMENT
      # -------------------------
      - name: Verify rollout
        run: |
          kubectl rollout status deployment/order-service
          kubectl rollout status deployment/product-service
          kubectl rollout status deployment/inventory-service
          kubectl rollout status deployment/notification-service
          kubectl rollout status deployment/api-gateway
